language: node_js

node_js:
  - 12

env: 
  - 'DATABASE_URL=postgresql://postgres@localhost:5432/taxi_trips'

before_script:
  - npm install
  - psql -c 'create database  taxi_trip;' -U postgres
  - psql -U postgres -d taxi_trip -a -f ../sql/tables.sql
  - psql -U postgres -d taxi_trip -a -f ../sql/data.sql

services:
  - postgresql
addons:
  postgresql: '9.4'
  apt:
    packages:
      - postgresql-server-dev-9.4